- hosts: all
  tasks:
    - name: Create a VM from a template
      vmware_guest:
        hostname: 10.100.248.164
        username: administrator@vsphere.local
        password: VMware1!
        datacenter: DC1
        validate_certs: no
        folder: /VMs
        name: CentOS69-169 
        state: poweredon
        template: CentOS6.9-vc55
        disk:
        - size_gb: 20
          type: thin
          datastore: vt1vc55
        hardware:
          memory_mb: 2048
          num_cpus: 1
          scsi: paravirtual
        networks:
        - name: VTRST-VT06-10.100.248.160%2f27
          ip: 10.100.248.169
          netmask: 255.255.255.224
          gateway: 10.100.248.161
          domain: vt.local
          type: static
      delegate_to: localhost
      register: deploy

